using System;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using SistemaMatricula.Models;
using SistemaMatricula.Helpers;

namespace SistemaMatricula.Controllers
{
    public class UserController : Controller
    {
        #region Auxiliary properties generated by the system
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public UserController()
        {
        }

        public UserController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        #endregion

        [Authorize(Roles = Models.User.ROLE_ADMINISTRATOR)]
        public ActionResult Index(User view)
        {
            ModelState.Clear();

            try
            {
                if (view.Pagination == null)
                    view.Pagination = new Pagination();

                ViewBag.List = Models.User.List(view);

                if (ViewBag.List == null)
                {
                    ViewBag.Message = "Não foi possível listar os registros. Erro de execução.";
                }
            }
            catch (Exception e)
            {
                string notes = string.Format("Filtro: {0}. Erro: {1}", view.Email, e.Message);
                Log.Add(Log.TYPE_ERROR, "SistemaMatricula.Controllers.UserController.Index", notes);
                ViewBag.Message = "Não foi possível realizar a solicitação. Erro de execução.";
            }

            return View(view);
        }

        [Authorize]
        public ActionResult Edit(RegisterViewModel view = null)
        {
            try
            {
                ViewBag.HideScreen = false;
                ViewBag.Title = "Manutenção de Usuários";

                ModelState.Clear();

                if (User.IsInRole(Models.User.ROLE_ADMINISTRATOR) == false)
                {
                    view.Login = Models.User.Logged.Login;
                    ViewBag.Title = "Alteração de senha";
                }

                view.RoleSelectList = new SelectList(Models.User.Roles());

                if (ModelState.IsValid == false)
                {
                    ViewBag.Message = "Não foi possível atualizar o registro. Analise os erros.";
                    return View("Edit", view);
                }

                if (string.IsNullOrWhiteSpace(view.Login))
                    return View("Edit", view);

                ApplicationUser user = UserManager.FindByName(view.Login);

                if (user == null)
                    throw new Exception("Registro não encontrado");

                view.Id = user.Id;
                view.Email = user.Email;

                var itens = UserManager.GetRoles(view.Id);

                if (itens.Count < 1)
                    throw new Exception("Registro não possui role cadastrado");

                view.RoleSelectList = new SelectList(Models.User.Roles(), itens[0]);
                view.RoleSelected = itens[0];
            }
            catch (Exception e)
            {
                string notes = string.Format("Parâmetro: {0}. Erro: {1}", view, e.Message);
                Log.Add(Log.TYPE_ERROR, "SistemaMatricula.Controllers.UserController.Edit", notes);
                ViewBag.Message = "Não foi possível realizar a solicitação. Erro de execução.";
                ViewBag.HideScreen = true;
            }

            return View("Edit", view);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Update(RegisterViewModel view)
        {
            try
            {
                if (ModelState.IsValid == false)
                    return Edit(view);

                ViewBag.HideScreen = false;

                view.Email = view.Email.Trim();
                view.Login = view.Login.Trim();

                if (User.IsInRole(Models.User.ROLE_ADMINISTRATOR) == false)
                    view.Login = User.Identity.GetUserName();

                var user = new ApplicationUser { UserName = view.Login, Email = view.Email };

                if (string.IsNullOrWhiteSpace(view.Id))
                {
                    var insert = await UserManager.CreateAsync(user, view.Password);

                    if (insert.Succeeded == false)
                    {
                        AddErrors(insert);
                        return Edit(view);
                    }

                    user = await UserManager.FindByNameAsync(user.UserName);
                    UserManager.AddToRole(user.Id, view.RoleSelected);

                    return RedirectToAction("Index", "User");
                }

                user = UserManager.FindByName(view.Login);

                if (user == null)
                    throw new Exception("Registro não encontrado");

                user.PasswordHash = UserManager.PasswordHasher.HashPassword(view.Password);

                var update = await UserManager.UpdateAsync(user);

                if (update.Succeeded == false)
                {
                    AddErrors(update);
                    return Edit(view);
                }

                return RedirectToAction("Index", "User");
            }
            catch (Exception e)
            {
                string notes = string.Format("Parâmetro: {0}. Erro: {1}", view, e.Message);
                Log.Add(Log.TYPE_ERROR, "SistemaMatricula.Controllers.UserController.Update", notes);
                ViewBag.Message = "Não foi possível realizar a solicitação. Erro de execução.";
                ViewBag.HideScreen = true;
            }

            return View("Edit");
        }

        [Authorize(Roles = Models.User.ROLE_ADMINISTRATOR)]
        public ActionResult Delete(Guid id)
        {
            try
            {
                if (Guid.Equals(id, Guid.Empty))
                    throw new Exception("Parâmetro vazio");

                var deleted = Models.User.Delete(id);

                if (deleted == false)
                    throw new Exception("Registro não apagado");

                return RedirectToAction("Index", "User");
            }
            catch (Exception e)
            {
                string notes = string.Format("View: {0}. Erro: {1}", id, e.Message);
                Log.Add(Log.TYPE_ERROR, "SistemaMatricula.Controllers.UserController.Delete", notes);
                ViewBag.Message = "Não foi possível realizar a solicitação. Erro de execução.";
                ViewBag.HideScreen = true;
            }

            return View("Index");
        }

        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            if (Request.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }

            ViewBag.ReturnUrl = returnUrl;

            return View("Login", "_Login");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(LoginViewModel model, string returnUrl)
        {
            if (ModelState.IsValid == false)
                return View("Login", "_Login", model);

            if (Models.User.IsActive(model.User) == false)
            {
                ModelState.AddModelError("", "Usuário inativo");
                return View("Login", "_Login", model);
            }

            var login = await SignInManager.PasswordSignInAsync(model.User, model.Password, model.RememberMe, shouldLockout: false);

            switch (login)
            {
                case SignInStatus.Success:
                    return RedirectToLocal(returnUrl);
                default:
                    ModelState.AddModelError("", "Tentativa de login inválida.");
                    return View("Login", "_Login", model);
            }
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult LogOff()
        {
            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);

            return RedirectToAction("Login", "User");
        }

        #region Auxiliary properties generated by the system
        // Usado para proteção XSRF ao adicionar logons externos
        private const string XsrfKey = "XsrfId";

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Index", "Home");
        }

        internal class ChallengeResult : HttpUnauthorizedResult
        {
            public ChallengeResult(string provider, string redirectUri)
                : this(provider, redirectUri, null)
            {
            }

            public ChallengeResult(string provider, string redirectUri, string userId)
            {
                LoginProvider = provider;
                RedirectUri = redirectUri;
                UserId = userId;
            }

            public string LoginProvider { get; set; }
            public string RedirectUri { get; set; }
            public string UserId { get; set; }

            public override void ExecuteResult(ControllerContext context)
            {
                var properties = new AuthenticationProperties { RedirectUri = RedirectUri };
                if (UserId != null)
                {
                    properties.Dictionary[XsrfKey] = UserId;
                }
                context.HttpContext.GetOwinContext().Authentication.Challenge(properties, LoginProvider);
            }
        }
        #endregion
    }
}