//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaMatricula.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<ClassData> ClassData { get; set; }
        public virtual DbSet<CourseData> CourseData { get; set; }
        public virtual DbSet<GridData> GridData { get; set; }
        public virtual DbSet<LogData> LogData { get; set; }
        public virtual DbSet<RegistryData> RegistryData { get; set; }
        public virtual DbSet<SemesterData> SemesterData { get; set; }
        public virtual DbSet<StudentData> StudentData { get; set; }
        public virtual DbSet<TeacherData> TeacherData { get; set; }
    }
}
