//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaMatricula.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GridData
    {
        public System.Guid IdGrid { get; set; }
        public System.Guid IdClass { get; set; }
        public System.Guid IdSemester { get; set; }
        public System.Guid IdTeacher { get; set; }
        public int Weekday { get; set; }
        public string Time { get; set; }
        public string Status { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public System.Guid RegisterBy { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<System.Guid> DeleteBy { get; set; }
    }
}
