//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaMatricula.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistryData
    {
        public System.Guid IdRegistry { get; set; }
        public System.Guid IdGrid { get; set; }
        public System.Guid IdStudent { get; set; }
        public Nullable<bool> Alternative { get; set; }
        public System.Guid RegisterBy { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<System.Guid> DeleteBy { get; set; }
    }
}
